[package]
name = "proc-macro-attr"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.36"
syn = { version = "2.0.75", features = ["extra-traits"] }
proc-macro2 = "1.0.86"

[lib]
proc-macro = true
